### PR TITLE
Now works out of the box

### PR DESCRIPTION
**Pull request by boada**
PEP8 compliance across all python files.
Fixed several python3 compatibility issues. 
Fixed `setup.py` not installing reference files when installing from source.

Now you can clone the repo, download the models, install, and the example should run without problems. Before this was not the case. For example see https://github.com/cmancone/easyGalaxy/issues/2.

### CODE REVIEW

**Comment by cmancone** [comment]
Thanks @boada I'm not sure why but I'm only just now seeing this pull request.  Either github didn't send me an email notification, or it got buried in my inbox.  I'm a bit slammed at work this week, but I'll aim to take a look at this in the next week or so and make sure all tests are still passing.  If so and everything looks good, I'll happily merge it and push out a new version.

**Comment by mwalmsley** [comment]
Gentle bump - I had similar problems and, after working around them, went to submit a PR and found that @boada has already done so (and done a better job). Great package, very useful!

**Comment by cmancone** [comment]
Hi guys,

One issue I've had with attempts to make it python3 compatible in the past is that it breaks python2.7 support.  It makes me suspect that what is really needed is a fork of this for python3.  Can you guys confirm that this doesn't break ezgal for python2 (granted, I can probably confirm that myself, but I'm in the middle of a large release at work).

In particular, test coverage these days is pretty good.  Did you make sure that the tests still work in python3?

**Comment by boada** [comment]
@cmancone I updated the tests in https://github.com/cmancone/easyGalaxy/pull/3/commits/43360df3dbeefc4169cf9e3e2a4ab8e66760ed61

boada> python2.7 test.py
.......................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 215 tests in 0.826s

OK

boada> python3.6 test.py
.......................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 215 tests in 0.856s

OK

**Comment by cmancone** [comment]
Thanks.  I'll have to create a new build and get it up to pip, but for the moment we can at least get it merged into master.

**Pull request merged**
